//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int CHAMCONGID { get; set; }
        public int NHANVIENID { get; set; }
        public System.DateTime NGAYCHAMCONG { get; set; }
        public Nullable<System.DateTime> GIOVAO { get; set; }
        public Nullable<System.DateTime> GIORA { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
