//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYEN_SANXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYEN_SANXUAT()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int CHUYENID { get; set; }
        public int PHANXUONGID { get; set; }
        public string MACHUYEN { get; set; }
        public string TENCHUYEN { get; set; }
        public bool DANGHOATDONG { get; set; }
    
        public virtual PHANXUONG PHANXUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
