//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIAKPI
    {
        public int DANHGIAID { get; set; }
        public int NHANVIENID { get; set; }
        public string KYDANHGIA { get; set; }
        public Nullable<decimal> DIEMHIEUSUAT { get; set; }
        public Nullable<decimal> DIEMCHUYENCAN { get; set; }
        public Nullable<decimal> DIEMTONGKET { get; set; }
        public string NHANXET { get; set; }
        public Nullable<int> NGUOIDANHGIA { get; set; }
        public System.DateTime NGAYDANHGIA { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
