//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONNGHIPHEP
    {
        public int DONNGHIPHEPID { get; set; }
        public int NHANVIENID { get; set; }
        public string LOAINGHIPHEP { get; set; }
        public System.DateTime TUNGAY { get; set; }
        public System.DateTime DENNGAY { get; set; }
        public string LYDO { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> NGUOIDUYET { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
