//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public int HOPDONGID { get; set; }
        public int NHANVIENID { get; set; }
        public string SOHOPDONG { get; set; }
        public string LOAIHOPDONG { get; set; }
        public System.DateTime TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public decimal MUCLUONG { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
