//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRM_DBEntities : DbContext
    {
        public HRM_DBEntities()
            : base("name=HRM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAMCONG> CHAMCONGs { get; set; }
        public virtual DbSet<DANHGIAKPI> DANHGIAKPIs { get; set; }
        public virtual DbSet<DONNGHIPHEP> DONNGHIPHEPs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<VAITRO> VAITROes { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUYEN_SANXUAT> CHUYEN_SANXUAT { get; set; }
        public virtual DbSet<DONVI_NHAMAY> DONVI_NHAMAY { get; set; }
        public virtual DbSet<PHANXUONG> PHANXUONGs { get; set; }
    }
}
