//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANXUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHANXUONG()
        {
            this.CHUYEN_SANXUAT = new HashSet<CHUYEN_SANXUAT>();
        }
    
        public int PHANXUONGID { get; set; }
        public int DONVIID { get; set; }
        public string TENPHANXUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYEN_SANXUAT> CHUYEN_SANXUAT { get; set; }
        public virtual DONVI_NHAMAY DONVI_NHAMAY { get; set; }
    }
}
