//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int TAIKHOANID { get; set; }
        public int VAITROID { get; set; }
        public int NHANVIENID { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string EMAIL { get; set; }
        public bool DANGHOATDONG { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
